# Generated by Django 5.1 on 2024-09-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
