# Generated by Django 5.1 on 2024-09-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_cart_cartitem_cart_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
