# Generated by Django 5.1 on 2024-09-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_product_quantity'),
    ]

    operations = [
    ]
