# Generated by Django 5.1 on 2024-09-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_auto_20240917_1208'),
    ]

    operations = [
    ]
